neutral_site_fields = ['Azteca Stadium', 'Estadio Azteca', 'Tottenham Hotspur', 
  'Tottenham Hotspur Stadium', 'Twickenham', 'Twickenham Stadium', 'Wembley', 
  'Wembley Stadium']

standardized_field_names = {
  'Arrowhead Stadium': 'Arrowhead Stadium',
  'AT&T': 'AT&T Stadium',
  'AT&T Stadium': 'AT&T Stadium',
  'Bank of America': 'Bank of America Stadium',
  'Bank of America Stadium': 'Bank of America Stadium',
  'Broncos Stadium at Mile High': 'Broncos Stadium',
  'Broncos Stadium At Mile High': 'Broncos Stadium',
  'Empower Field at Mile High': 'Broncos Stadium',
  'Sports Authority Field': 'Broncos Stadium',
  'Sports Authority Field at Mile High': 'Broncos Stadium',
  'CenturyField': 'CenturyLink Field',
  'CenturyLink': 'CenturyLink Field',
  'CenturyLink Field': 'CenturyLink Field',
  'Dignity Health Sports Park': 'Dignity Health Sports Park',
  'StubHub Center': 'Dignity Health Sports Park',
  'Edward Jones Dome': 'Edward Jones Dome',
  'FedExField': 'FedExField',
  'FedexField': 'FedExField',
  'First Energy Stadium': 'FirstEnergy Stadium',
  'FirstEnergy': 'FirstEnergy Stadium',
  'FirstEnergy Stadium': 'FirstEnergy Stadium',
  'FirstEnergyStadium': 'FirstEnergy Stadium',
  'Ford Field': 'Ford Field',
  'Georgia Dome': 'Georgia Dome',
  'Gillette Stadium': 'Gillette Stadium',
  'Hard Rock Stadium': 'Hard Rock Stadium',
  'Sun Life Stadium': 'Hard Rock Stadium',
  'Heinz Field': 'Heinz Field',
  'Lambeau Field': 'Lambeau Field',
  'Lambeau field': 'Lambeau Field',
  "Levi's Stadium": "Levi's Stadium",
  'Lincoln Finacial Field': 'Lincoln Financial Field',
  'Lincoln Financial Field': 'Lincoln Financial Field',
  'Los Angeles Memorial Coliesum': 'Los Angeles Memorial Coliseum',
  'Los Angeles Memorial Coliseum': 'Los Angeles Memorial Coliseum',
  'Lucas Oil': 'Lucas Oil Stadium',
  'Lucas Oil Stadium': 'Lucas Oil Stadium',
  'M & T Bank Stadium': 'M&T Bank Stadium',
  'M&T Bank Stadium': 'M&T Bank Stadium',
  'M&T Stadium': 'M&T Bank Stadium',
  'Mercedes Benz-Superdome': 'Mercedes-Benz Superdome',
  'Mercedes-Benz Dome': 'Mercedes-Benz Superdome',
  'Mercedes-Benz Superdome': 'Mercedes-Benz Superdome',
  'Mercedes-Benz Stadium': 'Mercedes-Benz Stadium',
  'MetLife': 'MetLife Stadium',
  'MetLife Stadium': 'MetLife Stadium',
  'Metlife Stadium': 'MetLife Stadium',
  'New Era Field': 'New Era Field',
  'Ralph Wilson Stadium': 'New Era Field',
  'Nissan Stadium': 'Nissan Stadium',
  'NRG': 'NRG Stadium',
  'NRG Stadiium': 'NRG Stadium',
  'NRG Stadium': 'NRG Stadium',
  'O.co Coliseum': 'Oakland-Alameda County Coliseum',
  'Oakland Alameda County Coliseum': 'Oakland-Alameda County Coliseum',
  'Oakland Alameda-County Coliseum': 'Oakland-Alameda County Coliseum',
  'Oakland-Alameda County Coliseum': 'Oakland-Alameda County Coliseum',
  'Paul Brown Stadium': 'Paul Brown Stadium',
  'Paul Brown Stdium': 'Paul Brown Stadium',
  'Qualcomm Stadium': 'Qualcomm Stadium',
  'Raymond James Stadium': 'Raymond James Stadium',
  'Soldier Field': 'Soldier Field',
  'Solider Field': 'Soldier Field',
  'Solidier Field': 'Soldier Field',
  'State Farm Stadium': 'State Farm Stadium',
  'Univerity of Phoenix Stadium': 'State Farm Stadium',
  'University of Phoeinx Stadium': 'State Farm Stadium',
  'University of Phoenix': 'State Farm Stadium',
  'University of Phoenix Stadium': 'State Farm Stadium',
  'Unviversity of Phoenix Stadium': 'State Farm Stadium',
  'TCF Bank Stadium': 'TCF Bank Stadium',
  'TIAA Bank Field': 'TIAA Bank Field',
  'EverBank Field': 'TIAA Bank Field',
  'Everbank Field': 'TIAA Bank Field',
  'U.S. Bank Stadium': 'U.S. Bank Stadium',
  'US Bank Stadium': 'U.S. Bank Stadium'
}

stadium_capacities = {
  'Arrowhead Stadium': 76416,
  'AT&T Stadium': 105000,
  'Bank of America Stadium': 75523,
  'Broncos Stadium': 76125,
  'CenturyLink Field': 68740,
  'Dignity Health Sports Park': 27000,
  'Edward Jones Dome': 67277,
  'FedExField': 82000,
  'FirstEnergy Stadium': 67895,
  'Ford Field': 65000,
  'Georgia Dome': 71228,
  'Gillette Stadium': 65878,
  'Hard Rock Stadium': 64767,
  'Heinz Field': 68400,
  'Lambeau Field': 81441,
  "Levi's Stadium": 68500,
  'Lincoln Financial Field': 69796,
  'Los Angeles Memorial Coliseum': 77500,
  'Lucas Oil Stadium': 67000,
  'M&T Bank Stadium': 71008,
  'Mercedes-Benz Superdome': 73208,
  'Mercedes-Benz Stadium': 71000,
  'MetLife Stadium': 82500,
  'New Era Field': 71608,
  'Nissan Stadium': 69143,
  'NRG Stadium': 72220,
  'Oakland-Alameda County Coliseum': 56057,
  'Paul Brown Stadium': 65515,
  'Qualcomm Stadium': 70561,
  'Raymond James Stadium': 65618,
  'Soldier Field': 61500,
  'State Farm Stadium': 63400,
  'TCF Bank Stadium': 50805,
  'TIAA Bank Field': 67814,
  'U.S. Bank Stadium': 66655
}